=== npgr/react-project-mgmt/resources/rest-definitions/schemas/project/list.json
{
    "$schema": "http://json-schema.org/schema",
    "description": "A project Detail",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "integer",
                "format": "longInteger"    
            },
            "name": {
                "type": "string",
                "format": "projectName"    
            },
            "customer": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "format": "longInteger"    
                  },
                  "name": {
                      "type": "string",
                      "format": "companyName"    
                  }
                },
                "required": [
                  "id",
                  "name"
                ] 
            },
            "status": {
              "type": "string",
              "format": "projectStatus"
            }
        },
        "required": [
          "id",
          "name",
          "customer",
          "status"
      ]
    }
}

=== npgr/react-project-mgmt/resources/stubs/projects/projects.json
[{
  "id": 72934,
  "name": "Project Stark and Sons",
  "customer": {
    "id": 11188,
    "name": "Hansen, Hayes and Ruecker"
  },
  "status": "inactive"
}, {
  "id": 18802,
  "name": "Project McKenzie, Lesch and Marquardt",
  "customer": {
    "id": 55123,
    "name": "Friesen - Kozey"
  },
  "status": "inactive"
}, {
  "id": 19661,
  "name": "Project Jast - Howe",
  "customer": {
    "id": 20054,
    "name": "Hackett - Yundt"
  },
  "status": "active"
}, {
  "id": 46202,
  "name": "Project Bruen Inc",
  "customer": {
    "id": 28206,
    "name": "Lubowitz - Kuhic"
  },
  "status": "inactive"
}, {
  "id": 64939,
  "name": "Project Rempel Group",
  "customer": {
    "id": 42893,
    "name": "Lehner - Mosciski"
  },
  "status": "inactive"
}]
